name: mangaz
description: "Projeto MangaZ - Leitor de Mangá Offline"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Compatível com o Dart 3.0.6 do GitHub

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  file_picker: ^10.3.10
  dio: ^5.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/Baner Lateral.png
    - assets/images/Logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.png"
  min_sdk_android: 21