name: mangaz
description: "Projeto MangaZ - Leitor de MangÃ¡ Offline"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.4
  share_plus: ^10.1.2
  file_picker: ^10.0.1
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/Baner Lateral.png
    - assets/images/Logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.png"
  min_sdk_android: 21