name: mangaz
description: "Projeto MangaZ - Leitor de Mangá Offline"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0            # Versão compatível
  url_launcher: ^6.1.11    # Versão compatível
  path_provider: ^2.0.15   # Versão compatível
  share_plus: ^7.1.0       # Versão compatível
  file_picker: ^6.1.1      # ESTE É O CONSERTO: Versão que aceita Dart 3.0.0
  dio: ^5.2.1              # Versão compatível

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/Baner Lateral.png
    - assets/images/Logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.png"
  min_sdk_android: 21