name: Gerar APK MangaZ

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Atualizado para v4

      - name: Instalar Java
        uses: actions/setup-java@v4 # Atualizado para v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.8'

      - name: Baixar dependências
        run: flutter pub get

      - name: Gerar o APK
        run: flutter build apk --release --split-per-abi

      - name: Disponibilizar o arquivo
        uses: actions/upload-artifact@v4 # O GRANDE CONSERTO ESTÁ AQUI
        with:
          name: manga-z-app
          # O caminho abaixo pega todos os APKs gerados pelo split
          path: build/app/outputs/flutter-apk/*.apk