name: Gerar APK MangaZ

on:
  push:
    branches:
      - main # O robô vai trabalhar toda vez que você der push na branch main
  workflow_dispatch: # Permite que você clique num botão para gerar o APK manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.8' # Versão que você está usando no pubspec

      - name: Baixar dependências
        run: flutter pub get

      - name: Gerar o APK
        run: flutter build apk --release --split-per-abi # Gera um APK mais leve

      - name: Disponibilizar o arquivo
        uses: actions/upload-artifact@v3
        with:
          name: manga-z-app
          path: build/app/outputs/flutter-apk/app-release.apk