name: Gerar APK MangaZ

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Flutter (Última Versão)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Sem fixar versão, ele pega a última de hoje
          cache: true

      - name: Baixar dependências
        run: flutter pub get

      - name: Gerar o APK
        run: flutter build apk --release --split-per-abi

      - name: Disponibilizar o arquivo
        uses: actions/upload-artifact@v4
        with:
          name: manga-z-app
          path: build/app/outputs/flutter-apk/*.apk